/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nodejs_core_NodeJSCore */

#ifndef _Included_org_nodejs_core_NodeJSCore
#define _Included_org_nodejs_core_NodeJSCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nodejs_core_NodeJSCore
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_nodejs_core_NodeJSCore_run
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
